#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FEATURES="$ROOT/kernel/config/features.hpp"
AHCI="$ROOT/kernel/storage/ahci.cpp"
MMIO="$ROOT/kernel/mm/mmio.cpp"
MEM="$ROOT/kernel/mm/memory.cpp"
VOLUME="$ROOT/kernel/storage/volume.cpp"
IDENTIFY="$ROOT/kernel/storage/identify.cpp"
PROBE="$ROOT/kernel/storage/disk_probe.cpp"
ROOTTRUST="$ROOT/kernel/security/root_trust.hpp"
QEMU="$ROOT/scripts/run-qemu.sh"
LIMINE="$ROOT/kernel/boot/limine_requests.cpp"

forbid_grep(){
  local pattern="$1"; shift
  if grep -R -E --line-number "$pattern" "$@" >/dev/null 2>&1; then
    echo "FAIL: forbidden pattern present: $pattern" >&2
    grep -R -E --line-number "$pattern" "$@" >&2 || true
    exit 1
  fi
}

[[ ! -e "$ROOT/kernel/storage/boot_control.cpp" ]]
[[ ! -e "$ROOT/kernel/security/rollback.cpp" ]]
grep -q 'PEREGRINUS_RELEASE_CURRENT_GENERATION' "$ROOT/include/peregrinus/release_profile.h"
grep -q 'ahci_dma_read_live=false' "$FEATURES"
grep -q 'recovery_journal_commit_live=false' "$FEATURES"
grep -q 'recovery_journal_write_test_live=false' "$FEATURES"
grep -q 'itco_watchdog_arm_live=false' "$FEATURES"
grep -q 'storage_write_enabled=false' "$FEATURES"
grep -q 'gpt_repair_enabled=false' "$FEATURES"
grep -q 'recovery_write_enabled=false' "$FEATURES"
grep -q 'ATA_CMD_WRITE_DMA_EXT=0x35' "$AHCI"
grep -q 'ATA_CMD_FLUSH_EXT=0xEA' "$AHCI"
grep -q 'features::recovery_journal_write_live' "$AHCI"
forbid_grep 'ATA_CMD_DATA_SET_MANAGEMENT|TRIM|WRITE_FUA|WRITE_QUEUED' "$ROOT/kernel/storage" --include='*.cpp' --include='*.hpp'
grep -q 'lba!=recovery_first_lba+2u&&lba!=recovery_last_lba-2u' "$AHCI"
grep -q 'readonly=true' "$VOLUME"
grep -q 'relative_lba>=v.sector_count' "$VOLUME"
grep -q 'snapshot=on' "$QEMU"
grep -q 'LIMINE_BASE_REVISION(5)' "$LIMINE"
grep -q 'mmio::map' "$AHCI"
if grep -q 'hhdm_offset' "$AHCI"; then echo 'FAIL: AHCI must not map MMIO via HHDM' >&2; exit 1; fi
grep -q 'alloc_dma32_page' "$AHCI"
grep -q 'ATA_CMD_IDENTIFY_DEVICE=0xEC' "$AHCI"
grep -q 'logical_sector_bytes' "$IDENTIFY"
grep -q 'read_metadata_sector_guarded' "$AHCI"
grep -q 'read_recovery_anchor_sector_guarded' "$AHCI"
grep -q 'read_recovery_journal_sector_guarded' "$AHCI"
grep -q 'write_recovery_journal_sector_guarded' "$AHCI"
grep -q 'gpt_backup_metadata_sectors' "$FEATURES"
grep -q 'SPLIT-BRAIN; automatic selection blocked' "$PROBE"
grep -q 'PAT3 is not UC; mapping blocked' "$MMIO"
grep -q 'features::dma32_required' "$MEM"
forbid_grep 'qemu_legacy_mmio_test' "$ROOT/kernel"
grep -q 'HALT-FAIL-CLOSED' "$ROOT/kernel/storage/boot_policy.cpp"
grep -q 'SPLIT-BRAIN' "$ROOT/kernel/storage/boot_policy.cpp"
grep -q 'NO-LKG' "$ROOT/kernel/storage/boot_policy.cpp"
grep -q 'minimum_security_epoch' "$ROOTTRUST"
forbid_grep 'evaluate_generation' "$ROOT/kernel"
CTRL="$ROOT/bootctl/uefi/trusted_boot_controller.c"
REQ="$ROOT/bootctl/common/boot_request.h"
grep -q 'n_secure_boot' "$CTRL"
grep -q 'n_setup_mode' "$CTRL"
grep -q 'n_oneshot' "$CTRL"
grep -q 'e_lkg' "$CTRL"
grep -q 'limine_staged_path' "$CTRL"
grep -q 'limine_committed_path' "$CTRL"
grep -q 'PEREGRINUS_TPM_COMMIT_BASE' "$ROOT/bootctl/common/tpm_commit.h"
forbid_grep 'TPM_CC_NV_Increment|TPM2_NV_Increment|0x00000134' "$ROOT/bootctl" "$ROOT/kernel"
grep -q 'PEREGRINUS_RELEASE_MIN_SECURITY_EPOCH' "$REQ"
grep -q 'PEREGRINUS_RECOVERY_JOURNAL_LIVE 0' "$CTRL"
grep -q 'g_block_io' "$CTRL"
grep -q 'g_partition_info' "$CTRL"
grep -q 'IA_RECOVERY Block I/O not found on boot disk; FAIL-CLOSED' "$CTRL"
grep -q 'WriteBlocks' "$CTRL"
grep -q 'FlushBlocks' "$CTRL"
grep -q 'ctx->bio->Media->LastBlock-2' "$CTRL"
forbid_grep 'PeregrinusBootSuccess' "$ROOT/kernel" "$ROOT/bootctl" "$ROOT/include"
grep -q 'confirm_boot_success' "$ROOT/kernel/storage/recovery_journal_probe.cpp"
grep -q 'recovery_journal_commit_live' "$ROOT/kernel/main.cpp"
grep -q 'firewall_default_deny=true' "$FEATURES"
grep -q 'firewall_frame_hook_foundation=true' "$FEATURES"
grep -q 'PEREGRINUS_QEMU_E1000_SANDBOX' "$FEATURES"
grep -q 'firewall_packet_hook_live=false' "$FEATURES"
grep -q 'firewall_stateful_tracking_live=false' "$FEATURES"
grep -q 'nic_driver_live=false' "$FEATURES"
grep -q 'ipv6_live=false' "$FEATURES"
grep -q 'nat_live=false' "$FEATURES"
grep -q 'dhcp_live=false' "$FEATURES"
grep -q 'Reason::default_deny' "$ROOT/kernel/security/firewall.cpp"
grep -q 'fragment_unsupported' "$ROOT/kernel/security/firewall.cpp"
forbid_grep 'io::out|io::in' "$ROOT/kernel/net"
# recovery-live must be able to read GPT (read-only) or it can never reach boot health.
grep -q 'ahci_dma_read_live || !features::recovery_metadata_live' "$ROOT/kernel/storage/disk_probe.cpp"
echo 'PASS: Muro 1.0.1 SAFE gates verified; live e1000 code exists only behind explicit qualification macro.'
